### PR TITLE
Migrated app to Expo

### PR DESCRIPTION
**Pull request by mgscreativa**
I have added some brand assets for the Expo publication, feel free to remove if you want.

### CODE REVIEW

**Comment by 39otrebla** [comment]
@mgscreativa thank you for publishing this on Expo, really appreciated. We don't want to have sample app working only for expo though. Could you consider to maintain a different branch? i.e. we maintain `master` while you keep up `expo` branch. 
Thanks.

**Comment by 39otrebla** [comment]
@mgscreativa I merged your pr in the `expo` branch and added reference to it in master's README.
Thank you again.

**Comment by mgscreativa** [comment]
Hi! I certainly can maintain the expo branch but please consider the code rework/refactoring Inhave done. That can make the maintenance a lot waster as it's just a copy/paste from future code.

Thanks!

**Comment by 39otrebla** [comment]
Sorry don't see what you are saying.

**Comment by mgscreativa** [comment]
If you take a look at the code, you'll see that some code refactoring was done, i.e.: created the App directory, no need to .bind(this), code reformat with prettier, assets folder organized, some branding app icons and splash (feel free to change it), etc.

If you keep that structure, the maintenance would be way too easy for me...

**Comment by 39otrebla** [comment]
Sure, I will look at it.

**Pull request merged**
